# Generated by Django 2.2.6 on 2019-10-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvintegration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='id',
        ),
        migrations.AlterField(
            model_name='university',
            name='rnc',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='RNC'),
        ),
    ]
