# Generated by Django 2.2.6 on 2019-10-12 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvintegration', '0003_auto_20191012_0331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carreer',
            old_name='closingDate',
            new_name='closing_date',
        ),
        migrations.RenameField(
            model_name='carreer',
            old_name='openingDate',
            new_name='opening_date',
        ),
    ]
